version: '3.10'

services:
  web:
    build: .
    command: gunicorn drf_api.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/code
    ports:
      - "8000:8000"

    depends_on:
      - db


  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: